name: intelliinteriors
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
  flutter_login_facebook: ^1.9.0
  google_sign_in: ^6.2.1
  flutter_svg_provider: ^1.0.3
  intl: ^0.18.1
  permission_handler: ^10.0.0
  file_picker: ^4.6.1
  dio: ^5.0.3
  fluttertoast: ^8.0.8
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoBlack.ttf
          weight: 900
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
    - family: Rubik
      fonts: 
        - asset: assets/fonts/RubikMedium.ttf
          weight: 500
